# Configuración para eureka-server

server:
  port: 8761

spring:
  application:
    name: eureka-server

# Eureka Server NO debe registrarse a sí mismo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false  # Desactivar auto-preservación en desarrollo
    eviction-interval-timer-in-ms: 4000  # Tiempo de verificación de servicios

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
